version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ../.env
    ports: 
      - "${API_PORT}:8000"

    volumes:
      - ../app/:/app/

    depends_on:
      database

    command: "uvicorn --factory application.api.main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"
