version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ../.env
    ports: 
      - "${APP_PORT}:8000"
    volumes:
      - ..:/app/

    command: "uvicorn --factory main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"
