version: '3.9'

services:
  mongo-express:
    image: mongo-express
    container_name: mongoui
    restart: always
    ports:
      - 28081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:?}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:?}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:?}:${MONGO_INITDB_ROOT_PASSWORD:?}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
