version: '3.9'

services:
  mongodb:
    image: mongo:6-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true

volumes:
  mongo_data:
