version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: database
    env_file:
      - ../.env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

