version: '3.9'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: worker
    env_file:
      - ../.env
    depends_on:
      - redis
    volumes:
      - ..:/app/
    command: taskiq worker -r app.infra.queues.taskiq.broker:broker app.infra.queues.taskiq.tasks

  scheduler:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: scheduler
    env_file:
      - ../.env
    depends_on:
      - redis
    volumes:
      - ..:/app/
    command: taskiq scheduler app.infra.queues.taskiq.broker:scheduler app.infra.queues.taskiq.tasks

volumes:
  redis_data: