"""update type model

Revision ID: acec9144574f
Revises: c26a6fd9e8b6
Create Date: 2024-06-20 16:48:50.317684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acec9144574f'
down_revision: Union[str, None] = 'c26a6fd9e8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'package_types', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package_types', type_='unique')
    # ### end Alembic commands ###
